/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#131b2e",
        "on-secondary-container": "#b0b2ff",
        "on-background": "#dae2fd",
        "background": "#0b1326",
        "tertiary": "#4edea3",
        "primary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#2d3449",
        "on-secondary": "#1000a9",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#3d494c",
        "on-primary": "#003640",
        "inverse-primary": "#00687a",
        "secondary": "#c0c1ff",
        "surface-bright": "#31394d",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#003824",
        "inverse-surface": "#dae2fd",
        "surface-container": "#171f33",
        "secondary-fixed": "#e1e0ff",
        "secondary-container": "#3131c0",
        "outline": "#869397",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004e5c",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-variant": "#2d3449",
        "tertiary-container": "#1bbd85",
        "on-secondary-fixed-variant": "#2f2ebe",
        "secondary-fixed-dim": "#c0c1ff",
        "inverse-on-surface": "#283044",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#00452e",
        "surface": "#0b1326",
        "surface-dim": "#0b1326",
        "on-primary-fixed": "#001f26",
        "surface-container-lowest": "#060e20",
        "primary-fixed": "#acedff",
        "on-secondary-fixed": "#07006c",
        "on-surface": "#dae2fd",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-high": "#222a3d",
        "on-primary-container": "#00424f",
        "primary-container": "#06b6d4",
        "on-tertiary-fixed": "#002113",
        "on-surface-variant": "#bcc9cd",
        "primary": "#4cd7f6",
        "surface-tint": "#4cd7f6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-tablet": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "margin-desktop": "2rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "space-md": "0.75rem"
      },
      fontFamily: {
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-ui": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-code-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-ui": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
